language: python
sudo: false
branches:
  only:
    - master
python:
  - "3.6"

install:
  - pip install --upgrade setuptools
  - pip install -r requirements.txt

before_script: git lfs pull

script: 
  - py.test piviz --cov=piviz

after_success:
  - coveralls